class AppStrings {
  static Map<String, Map<String, String>> text = {
    "en": {
      "dashboard": "Dashboard",
      "welcome": "Welcome",
      "monitoring": "Real-time Security Monitoring",
      "onlineUsers": "Online Users",
      "activeAlerts": "Active Alerts",
      "devices": "Devices",
      "announcement": "Announcement Page",
      "emergency": "Emergency Dashboard",
      "notifications": "Notifications",
      "darkMode": "Dark Mode",
      "lightMode": "Light Mode",
      "live": "Live",
      "profile": "Profile",
      "role": "Role",
      "phone": "Phone",
      "switchToArabic": "Switch to Arabic",
      "switchToEnglish": "Switch to English",
      "profileAddPhoto": "Tap to add photo",
      "personalInfo": "Personal Information",
      "personalInfoDesc": "View and edit your details",
      "securityPassword": "Security & Password",
      "securityPasswordDesc": "Manage your password and security",
      "workInfo": "Work Information",
      "workInfoDesc": "View department and location",
      "notificationSettings": "Notifications Settings",
      "notificationSettingsDesc": "Manage notifications",
      "helpSupport": "Help & Support",
      "helpSupportDesc": "Get help and contact support",
      "privacySettings": "Privacy Settings",
      "privacySettingsDesc": "Control your privacy preferences",
      "logout": "Log Out",
      "logoutDesc": "Sign out of your account",
      "logoutConfirm": "Are you sure you want to log out?",
      "cancel": "Cancel",
      "confirm": "Yes",
      "welcomeBack": "Welcome Back",
      "securityTagline": "Security You Can Rely On",
      "emailLabel": "Email Address",
      "emailHint": "Enter your email",
      "emailRequired": "Email is required",
      "emailInvalid": "Enter a valid email",
      "passwordLabel": "Password",
      "passwordHint": "Enter your password",
      "passwordRequired": "Password is required",
      "passwordShort": "Password must be at least 6 characters",
      "loginButton": "Secure Login",
      "googleLoginButton": "Continue with Google",
      "forgotPassword": "Forgot password?",
      "createAccount": "Create Account",
      "registerSubtitle": "Create your secure monitoring account",
      "usernameLabel": "Username",
      "usernameHint": "Enter your username",
      "usernameRequired": "Username is required",
      "confirmPasswordLabel": "Confirm Password",
      "confirmPasswordHint": "Re-enter your password",
      "confirmPasswordRequired": "Please confirm your password",
      "passwordsDoNotMatch": "Passwords do not match",
      "registerButton": "Create Account",
      "alreadyHaveAccount": "Already have an account? Sign in",
      "registerSuccess": "Account created successfully. You can log in now.",
      "devicesTitle": "Connected Devices",
      "devicesSubtitle": "Live device records from the backend.",
      "registerDevice": "Register Device",
      "refresh": "Refresh",
      "deviceOwner": "Owner",
      "deviceLabel": "Device Label",
      "deviceCoordinates": "Coordinates",
      "deviceLatitude": "Latitude",
      "deviceLongitude": "Longitude",
      "save": "Save",
      "delete": "Delete",
      "details": "Details",
      "edit": "Edit",
      "noDevices": "No devices found yet.",
      "mapTitle": "Zone Overview",
      "mapSubtitle": "Live zones and recent events from the backend.",
      "recentEvents": "Recent Events",
      "zonesUnavailable": "Zones are unavailable right now.",
      "eventsUnavailable": "Events are unavailable for this account right now.",
    },
    "ar": {
      "dashboard": "لوحة التحكم",
      "welcome": "مرحبا",
      "monitoring": "مراقبة الأمن في الوقت الحقيقي",
      "onlineUsers": "المستخدمون المتصلون",
      "activeAlerts": "التنبيهات النشطة",
      "devices": "الأجهزة",
      "announcement": "صفحة الإعلانات",
      "emergency": "لوحة الطوارئ",
      "notifications": "الإشعارات",
      "darkMode": "الوضع الداكن",
      "lightMode": "الوضع الفاتح",
      "live": "مباشر",
      "profile": "الملف الشخصي",
      "role": "الدور",
      "phone": "الهاتف",
      "switchToArabic": "التبديل إلى العربية",
      "switchToEnglish": "Switch to English",
      "profileAddPhoto": "اضغط لإضافة صورة",
      "personalInfo": "المعلومات الشخصية",
      "personalInfoDesc": "عرض وتعديل بياناتك",
      "securityPassword": "الأمان وكلمة المرور",
      "securityPasswordDesc": "إدارة كلمة المرور والأمان",
      "workInfo": "معلومات العمل",
      "workInfoDesc": "عرض القسم والموقع",
      "notificationSettings": "إعدادات الإشعارات",
      "notificationSettingsDesc": "إدارة الإشعارات",
      "helpSupport": "المساعدة والدعم",
      "helpSupportDesc": "الحصول على المساعدة والتواصل مع الدعم",
      "privacySettings": "إعدادات الخصوصية",
      "privacySettingsDesc": "التحكم في تفضيلات الخصوصية",
      "logout": "تسجيل الخروج",
      "logoutDesc": "تسجيل الخروج من الحساب",
      "logoutConfirm": "هل أنت متأكد من رغبتك في تسجيل الخروج؟",
      "cancel": "إلغاء",
      "confirm": "نعم",
      "welcomeBack": "مرحبا بعودتك",
      "securityTagline": "أمان يمكنك الاعتماد عليه",
      "emailLabel": "البريد الإلكتروني",
      "emailHint": "أدخل بريدك الإلكتروني",
      "emailRequired": "البريد الإلكتروني مطلوب",
      "emailInvalid": "أدخل بريدًا إلكترونيًا صحيحًا",
      "passwordLabel": "كلمة المرور",
      "passwordHint": "أدخل كلمة المرور",
      "passwordRequired": "كلمة المرور مطلوبة",
      "passwordShort": "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
      "loginButton": "تسجيل الدخول الآمن",
      "googleLoginButton": "المتابعة عبر Google",
      "forgotPassword": "نسيت كلمة المرور؟",
      "createAccount": "إنشاء حساب",
      "registerSubtitle": "أنشئ حسابك الآمن للمراقبة",
      "usernameLabel": "اسم المستخدم",
      "usernameHint": "أدخل اسم المستخدم",
      "usernameRequired": "اسم المستخدم مطلوب",
      "confirmPasswordLabel": "تأكيد كلمة المرور",
      "confirmPasswordHint": "أعد إدخال كلمة المرور",
      "confirmPasswordRequired": "يرجى تأكيد كلمة المرور",
      "passwordsDoNotMatch": "كلمتا المرور غير متطابقتين",
      "registerButton": "إنشاء الحساب",
      "alreadyHaveAccount": "لديك حساب بالفعل؟ سجّل الدخول",
      "registerSuccess": "تم إنشاء الحساب بنجاح. يمكنك تسجيل الدخول الآن.",
      "devicesTitle": "الأجهزة المتصلة",
      "devicesSubtitle": "سجلات الأجهزة الحية من الـ backend.",
      "registerDevice": "تسجيل جهاز",
      "refresh": "تحديث",
      "deviceOwner": "المالك",
      "deviceLabel": "اسم الجهاز",
      "deviceCoordinates": "الإحداثيات",
      "deviceLatitude": "خط العرض",
      "deviceLongitude": "خط الطول",
      "save": "حفظ",
      "delete": "حذف",
      "details": "التفاصيل",
      "edit": "تعديل",
      "noDevices": "لا توجد أجهزة حتى الآن.",
      "mapTitle": "نظرة عامة على المناطق",
      "mapSubtitle": "المناطق والأحداث الحية من الـ backend.",
      "recentEvents": "الأحداث الأخيرة",
      "zonesUnavailable": "المناطق غير متاحة الآن.",
      "eventsUnavailable": "الأحداث غير متاحة لهذا الحساب الآن.",
    },
  };
}
